swagger: "2.0"
info:
  title: START Hack 2021
  version: "1.0.0"
consumes:
  - application/json
produces:
  - application/json

basePath: /

paths:
  /quote:
    get:
      summary: Get random quote
      operationId: api.get_quote
      responses:
        '200':
          description: random quote
  /health/{uid}:
    get:
      summary: Get health data
      operationId: api.get_health
      parameters:
        - in: path
          name: uid
          type: integer
          required: true
          description: User ID
      responses:
        '200':
          # description: OK
          description: Array of health data
          # content:
          #   application/json:
          #     schema:
          #       type: object
          #       properties:
          #         health:
          #           type: list
          #           description: Health data